version: '3.5'
services:
  atuin:
    restart: always
    build: container
    command: server start
    volumes:
      - "./config:/root/.config"
    links:
      - postgresql:db
    ports:
      - 8888:8888
        # - 8889:8889
    environment:
      ATUIN_HOST: "0.0.0.0"
      ATUIN_OPEN_REGISTRATION: "true"
      ATUIN_DB_URI: postgres://$ATUIN_DB_USERNAME:$ATUIN_DB_PASSWORD@db/$ATUIN_DB_NAME
  postgresql:
    image: postgres:15
    restart: unless-stopped
    volumes: # Don't remove permanent storage for index database files!
      - "./database:/var/lib/postgresql/data/"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: $ATUIN_DB_USERNAME
      POSTGRES_PASSWORD: $ATUIN_DB_PASSWORD
      POSTGRES_DB: $ATUIN_DB_NAME
